In [33]:
import numpy as np

In [34]:
Q_table=np.zeros((6,6))
Q_table=np.array(Q_table)
R_table=np.zeros((6,6))
print(Q_table,R_table)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]] [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


In [35]:
R_table=[[-1,-1,-1,-1,0,-1],
         [-1, -1, -1, 0, -1,100],
        [-1, -1, -1, 0, -1, -1],
        [-1, 0, 0, -1, 0, -1],
       [0, -1, -1, 0, -1, 100],
        [-1, -1, -1, -1, 0, 100]]
R_table=np.array(R_table)
print(R_table)

[[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1   0  -1]
 [  0  -1  -1   0  -1 100]
 [ -1  -1  -1  -1   0 100]]


In [36]:
print(R_table[:,0].max())
print(R_table[:,0])

0
[-1 -1 -1 -1  0 -1]


In [37]:
Q_table[3,1]=R_table[3,1]+0.8*Q_table[1,:].max()
print(Q_table)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


In [38]:
for x in range(0,500):
    for s in range (0,6):
        for a in range (0,6):
            if(R_table[s,a]>-1):
                Q_table[s,a]=R_table[s,a]+0.8*Q_table[a,:].max()
    print(Q_table)
           

[[   0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.  100.]
 [   0.    0.    0.    0.    0.    0.]
 [   0.   80.    0.    0.    0.    0.]
 [   0.    0.    0.   64.    0.  100.]
 [   0.    0.    0.    0.   80.  164.]]
[[   0.       0.       0.       0.      80.       0.   ]
 [   0.       0.       0.      64.       0.     231.2  ]
 [   0.       0.       0.      64.       0.       0.   ]
 [   0.     184.96    51.2      0.      80.       0.   ]
 [  64.       0.       0.     147.968    0.     231.2  ]
 [   0.       0.       0.       0.     184.96   247.968]]
[[   0.          0.          0.          0.        184.96        0.      ]
 [   0.          0.          0.        147.968       0.        298.3744  ]
 [   0.          0.          0.        147.968       0.          0.      ]
 [   0.        238.69952   118.3744      0.        184.96        0.      ]
 [ 147.968       0.          0.        190.959616    0.        298.3744  ]
 [   0.          0.          0.          0.    

 [   0.    0.    0.    0.  400.  500.]]
[[   0.    0.    0.    0.  400.    0.]
 [   0.    0.    0.  320.    0.  500.]
 [   0.    0.    0.  320.    0.    0.]
 [   0.  400.  256.    0.  400.    0.]
 [ 320.    0.    0.  320.    0.  500.]
 [   0.    0.    0.    0.  400.  500.]]
[[   0.    0.    0.    0.  400.    0.]
 [   0.    0.    0.  320.    0.  500.]
 [   0.    0.    0.  320.    0.    0.]
 [   0.  400.  256.    0.  400.    0.]
 [ 320.    0.    0.  320.    0.  500.]
 [   0.    0.    0.    0.  400.  500.]]
[[   0.    0.    0.    0.  400.    0.]
 [   0.    0.    0.  320.    0.  500.]
 [   0.    0.    0.  320.    0.    0.]
 [   0.  400.  256.    0.  400.    0.]
 [ 320.    0.    0.  320.    0.  500.]
 [   0.    0.    0.    0.  400.  500.]]
[[   0.    0.    0.    0.  400.    0.]
 [   0.    0.    0.  320.    0.  500.]
 [   0.    0.    0.  320.    0.    0.]
 [   0.  400.  256.    0.  400.    0.]
 [ 320.    0.    0.  320.    0.  500.]
 [   0.    0.    0.    0.  400.  500.]]
[[   0.    0.    0. 

In [39]:
print(Q_table/5)

[[   0.     0.     0.     0.    80.     0. ]
 [   0.     0.     0.    64.     0.   100. ]
 [   0.     0.     0.    64.     0.     0. ]
 [   0.    80.    51.2    0.    80.     0. ]
 [  64.     0.     0.    64.     0.   100. ]
 [   0.     0.     0.     0.    80.   100. ]]


In [ ]:
a=range(0,6)
for s in range (0,6):
    print(s)